# Q2.1

## One Vs All: 
#### One Vs All is also known as One vs Rest is a heuristic method for Binary classification algorithms in order to perform Multi-Class classification. It splitts the Multi-Class Dataset into multiple binary classification problem. After splitting the dataset into multiple binary classes it trains the binary classifier on each of the classes and then the prediction is made for the multiclass. 

## One vs One 
#### One vs One is another heuristic technique that is used for Multiclass Class classification using binary Classification. Similar to One Vs All it splits the dataset into one binary data for each class vs every other class.  

In [1]:
# Import the Necessary Packages 
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report 
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier


## Q2

In [2]:
# Load the DatasetB 
dataB = pd.read_csv('Dataset/DataB.csv')

In [3]:
# DataB Display
print("DataB: \n" ,dataB)

DataB: 
      sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]


In [4]:
# Check for Null values 
dataB.isna().sum()

sepallength    0
sepalwidth     0
petallength    0
petalwidth     0
class          0
dtype: int64

In [5]:
# Collect all the features of the DataB 
dataB_X = dataB.drop(['class'], axis=1)

In [6]:
dataB_X 

sepallength  sepalwidth  petallength  petalwidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [7]:
# Collect the Target Variables 
dataB_y = dataB['class']
print(" Target for the DataB: \n", dataB_y)

Target for the DataB: 
 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: class, Length: 150, dtype: object


In [8]:
# Check the Unique values in the Target
print("Unique Values in DataB: \n", dataB_y.unique())

Unique Values in DataB: 
 ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [9]:
# Transform the Labels to Numbers 
le = LabelEncoder()
dataB_y_num = le.fit_transform(dataB_y)

In [10]:
print(" Transformed Values of the Target: \n",dataB_y_num)

Transformed Values of the Target: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [11]:
# Split the dataset in the ratio of 70:30  
X_train, X_test, y_train, y_test = train_test_split(dataB_X, dataB_y_num, test_size = 0.30, random_state = 42)


In [12]:
# Standardise the dataset 
ss = StandardScaler()
X_train_std = ss.fit_transform(X_train)
X_test_std = ss.fit_transform(X_test)

## One vs all Classification  

In [13]:
# Initalize the Class with linear and One vs all method 
svm_ovr = SVC(kernel= 'linear', decision_function_shape= 'ovr')

In [14]:
# Train the dataset on the SVM classifier 
svm_ovr.fit(X_train_std, y_train)
y_pred_ovr = svm_ovr.predict(X_test_std)

In [15]:
# Accuracy Score 
acc_score = accuracy_score(y_test, y_pred_ovr)
print("Accuracy Score for One vs all Method: ", acc_score*100)

Accuracy Score for One vs all Method:  93.33333333333333


In [16]:
# Check the Categorical report for the Classifier 
print("Classification Report for the One Vs All Method Using Kernel = 'Linear': \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(y_pred_ovr)))

Classification Report for the One Vs All Method Using Kernel = 'Linear': 
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      0.77      0.87        13
 Iris-virginica       0.81      1.00      0.90        13

       accuracy                           0.93        45
      macro avg       0.94      0.92      0.92        45
   weighted avg       0.95      0.93      0.93        45



In [17]:
# Confusion Matrix for the predicted value 
print("Confusion Matrix for One Vs All Method: \n", confusion_matrix(y_test, y_pred_ovr))

Confusion Matrix for One Vs All Method: 
 [[19  0  0]
 [ 0 10  3]
 [ 0  0 13]]


## One vs One Classification 

In [18]:
# Initilaze the Classifier with one vs one method and linear kernel 
svm_ovo = SVC(kernel= 'linear', decision_function_shape= 'ovo')

In [19]:
# Train and Test the Dataset 
svm_ovo.fit(X_train_std, y_train)
y_pred_ovo = svm_ovo.predict(X_test_std)
acc_score_ovo = accuracy_score(y_test, y_pred_ovo)

In [20]:
# Check the Accuracy Score for the Dataset 
print("Accuracy_Score for One Vs One: ", acc_score_ovo*100)

Accuracy_Score for One Vs One:  93.33333333333333


In [21]:
# Check the Classification Report for the Classifier 
print("Classification Report for the One Vs All Method Using Kernel = 'Linear': \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(y_pred_ovo)))

Classification Report for the One Vs All Method Using Kernel = 'Linear': 
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      0.77      0.87        13
 Iris-virginica       0.81      1.00      0.90        13

       accuracy                           0.93        45
      macro avg       0.94      0.92      0.92        45
   weighted avg       0.95      0.93      0.93        45



In [22]:
# Check the Confusion Matrix for the Classifier 
print("Confusion Matrix for One Vs All Method: \n", confusion_matrix(y_test, y_pred_ovo))

Confusion Matrix for One Vs All Method: 
 [[19  0  0]
 [ 0 10  3]
 [ 0  0 13]]


## Decision Tree 

In [23]:
# Initialize the Classifier
dtclf = DecisionTreeClassifier()
dtclf.fit(X_train_std, y_train)
y_pred_DT = dtclf.predict(X_test_std)
DT_accuracy_store = accuracy_score(y_test, y_pred_DT)
print("Accuracy Score for Decision Tree: ", DT_accuracy_store*100)

Accuracy Score for Decision Tree:  86.66666666666667


In [24]:
# Check the Classification Report for the Classifier 
print("Classification Report for the One Vs All Method Using Kernel = 'Linear': \n", classification_report(le.inverse_transform(y_test), le.inverse_transform(y_pred_DT)))

Classification Report for the One Vs All Method Using Kernel = 'Linear': 
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      0.54      0.70        13
 Iris-virginica       0.68      1.00      0.81        13

       accuracy                           0.87        45
      macro avg       0.89      0.85      0.84        45
   weighted avg       0.91      0.87      0.86        45



In [25]:
# Check the Confusion Matrix for the Classifier 
print("Confusion Matrix for One Vs All Method: \n", confusion_matrix(y_test, y_pred_DT))

Confusion Matrix for One Vs All Method: 
 [[19  0  0]
 [ 0  7  6]
 [ 0  0 13]]


## Comment on the Result: 


In [26]:
from scipy.io import loadmat 

In [27]:
dataA = loadmat('Dataset/DataA.mat')

In [28]:
dataA

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Tue Oct 21 15:46:48 2014',
 '__version__': '1.0',
 '__globals__': [],
 'fea': array([[1, 2, 1, ..., 2, 2, 1],
        [3, 3, 4, ..., 1, 3, 4],
        [4, 1, 4, ..., 2, 4, 4],
        ...,
        [3, 4, 4, ..., 3, 1, 2],
        [1, 4, 3, ..., 4, 3, 4],
        [4, 3, 1, ..., 2, 4, 3]], dtype=uint8),
 'gnd': array([[1],
        [1],
        [1],
        ...,
        [1],
        [1],
        [1]], dtype=int16)}

In [29]:
dataA_dataframe = pd.DataFrame(np.hstack((dataA['fea'], dataA['gnd'])))

In [30]:
dataA_dataframe 

0   1   2   3   4   5   6   7   8   9   ...  48  49  50  51  52  53  54  \
0      1   2   1   2   1   2   3   3   3   3  ...   3   2   3   4   2   2   2   
1      3   3   4   2   1   2   2   4   3   2  ...   1   4   3   4   4   4   1   
2      4   1   4   4   4   4   1   1   2   1  ...   1   2   1   1   4   2   2   
3      1   4   1   1   3   3   4   4   3   4  ...   1   3   3   4   1   3   3   
4      3   4   4   3   1   1   4   4   4   1  ...   3   1   3   2   1   4   2   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
2195   3   3   3   4   2   2   3   3   4   4  ...   1   4   3   3   4   1   2   
2196   3   3   1   1   2   3   3   4   3   1  ...   2   1   3   1   2   3   4   
2197   3   4   4   3   3   3   1   2   4   3  ...   4   3   3   4   1   2   3   
2198   1   4   3   4   1   3   4   2   4   3  ...   2   4   2   2   2   4   4   
2199   4   3   1   2   2   3   3   3   3   4  ...   4   3   3   4   3   4   2   

      55  56  57  
0      2   1   1  
1      3   4   1  
2      4   4   1  
3      4   2  -1  
4      1   1  -1  
...   ..  ..  ..  
2195   1   3  -1  
2196   2   3  -1  
2197   1   2   1  
2198   3   4   1  
2199   4   3   1  

[2200 rows x 58 columns]